# Generated by Django 4.0.5 on 2022-06-29 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='date_receita',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 28, 21, 59, 2, 502117)),
        ),
    ]
